'use client';

import { useEffect, useLayoutEffect, useMemo, useRef } from 'react';
import { Box, Button, Stack, Typography } from '@mui/material';
import { createTimeline, cubicBezier, stagger, utils } from 'animejs';
import { prefersReducedMotion } from '@/lib/motion';
import { openChat } from '@/lib/chatBridge';
import type { HeroProps } from '@/components/Hero';

/**
 * The accession plate — the catalogue record for the collection itself.
 *
 * ── What the fold IS ────────────────────────────────────────────────────────
 * Not a headline over a background. A museum object label, set at plate size:
 * a stamped accession number, the object's name, and then the record proper —
 * DESIGNATION / PROVENANCE / MEDIUM — each a tracked-caps label against a
 * hairline against a row of values. That layout is lifted from the thing it
 * says it is: a printed catalogue entry, where the SPEC LIST is the content and
 * the typography's whole job is to make a list of facts feel considered.
 *
 * ── Where the copy comes from ───────────────────────────────────────────────
 * F1 still binds. Every résumé string below is authored in
 * `content/01-about/01-bio.md` (`title`, `headline`, `proof`, `highlights`) and
 * threaded in as props. Nothing is invented, and a field the content does not
 * declare renders NO ROW — never an empty label with a rule under it, which on
 * a page whose whole argument is rules would be the loudest possible bug.
 *
 * The one string authored here is the assistant line, which is chrome copy
 * about this page rather than a claim about the person — the same exception
 * `HeroA` documents. It is set as the pull quote precisely because it is the
 * contemporary thing: an on-device LLM, described in Newsreader italic on
 * cream. The archival frame is supposed to sit around content that pushes back.
 *
 * ── The motion ──────────────────────────────────────────────────────────────
 * One anime.js timeline, ~1.04s, played once, and then the fold is a still
 * printed object forever. There is NO requestAnimationFrame loop in this file
 * and nothing here loops: paper does not shimmer. Every scroll-linked effect in
 * this skin lives in CSS on the compositor (`animation-timeline: view()`),
 * because this page runs ONNX inference on the main thread and every frame this
 * skin does not ask for is a frame the assistant gets.
 */

/** The house curve for this skin, in the spelling anime.js 4 actually accepts. */
const EASE_OUT_QUINT = cubicBezier(0.22, 1, 0.36, 1);
const EASE_IN_OUT_QUART = cubicBezier(0.76, 0, 0.24, 1);

/**
 * Chrome copy about the page, not a résumé fact — see the note above.
 * Deliberately the most un-archival sentence available.
 */
const ASSISTANT_LINE =
    'The assistant in the corner answers questions about this résumé on your own GPU — the model runs in this tab, with no server.';

/**
 * The COLLECTION's accession year — not an item number, and not a claim about
 * the person.
 *
 * Museum numbering practice is `year.sequence`, four-digit year first, no zero
 * padding, and the year is the year the material was ACCESSIONED rather than
 * the year it was made. The individual objects on this page are therefore
 * `2026.1 … 2026.n`, generated by a CSS counter in `skin-accession.css`; the
 * stamp on the fold is the collection they belong to, so it carries the year
 * alone. `2026` is the current year of the collection, which the content
 * already asserts (`content/04-projects/09-harness.md` is dated 2026).
 */
const STAMP_YEAR = '2026';

/** Blank/whitespace-only frontmatter is absent, not an empty line. */
function text(value: string | undefined): string | undefined {
    const trimmed = value?.trim();
    return trimmed ? trimmed : undefined;
}

/**
 * A record value is a row of CELLS, not a sentence.
 *
 * The content already uses ` · ` as its field separator in `headline` and
 * `proof` — so the catalogue reading of those strings is not an interpretation
 * imposed on them, it is the separator they were already written with. Splitting
 * lets each fact sit in its own column between hairlines, which is what makes a
 * spec list read as specification rather than as prose with dots in it.
 */
function cells(value: string | undefined): string[] {
    return (value ?? '')
        .split('·')
        .map((s) => s.trim())
        .filter(Boolean);
}

interface RecordRow {
    label: string;
    values: string[];
}

/** The name, split so the surname can carry the italic. */
function splitName(name: string): [string, string] {
    const parts = name.trim().split(/\s+/);
    if (parts.length < 2) return [name, ''];
    return [parts.slice(0, -1).join(' '), parts[parts.length - 1]];
}

const useIsoLayoutEffect = typeof window !== 'undefined' ? useLayoutEffect : useEffect;

export default function AccessionHero({ about }: HeroProps) {
    const rootRef = useRef<HTMLElement | null>(null);

    const title = text(about?.title);
    const location = text(about?.location);
    const [given, family] = useMemo(() => splitName(title ?? ''), [title]);

    /**
     * The record, in the canonical museum object-label order: what it is, where
     * it came from, what it is made of. A row with no values is not rendered.
     */
    const record: RecordRow[] = useMemo(() => {
        const rows: RecordRow[] = [
            { label: 'Designation', values: cells(text(about?.headline)) },
            { label: 'Provenance', values: cells(text(about?.proof)) },
            {
                label: 'Medium',
                values: (about?.highlights ?? [])
                    .map(text)
                    .filter((t): t is string => Boolean(t)),
            },
        ];
        return rows.filter((r) => r.values.length > 0);
    }, [about?.headline, about?.proof, about?.highlights]);

    // ── The entrance: one timeline, once ────────────────────────────────────
    useIsoLayoutEffect(() => {
        const root = rootRef.current;
        if (!root) return;

        const rules = Array.from(root.querySelectorAll<HTMLElement>('.ac-rule'));
        const words = Array.from(root.querySelectorAll<HTMLElement>('.ac-word > span'));
        const risers = Array.from(root.querySelectorAll<HTMLElement>('[data-ac-rise]'));
        const stamp = root.querySelector<HTMLElement>('.ac-stamp');

        /**
         * Reduced motion is a gate, not a shorter duration: the plate is simply
         * already printed. Nothing is hidden — this branch sets no hidden state
         * at all, so the resting DOM (which is what the markup renders) stands.
         */
        if (prefersReducedMotion()) return;

        // The hidden state is applied HERE rather than in CSS because this hero
        // is `dynamic(ssr: false)`: it does not exist at first paint, so there
        // is no painted frame to flash. A `useLayoutEffect` runs before this
        // component's first paint, which is the only paint it has.
        utils.set(rules, { scaleX: 0 });
        utils.set(words, { opacity: 0, translateY: '108%' });
        utils.set(risers, { opacity: 0, translateY: 12 });
        if (stamp) utils.set(stamp, { opacity: 0, rotate: -7, scale: 1.09 });

        const tl = createTimeline({ defaults: { ease: EASE_OUT_QUINT } });

        // BEAT 3 — the rules draw first. A printed page is ruled before it is
        // set, and 100ms of empty ruled plate is what makes the name land ON
        // something instead of arriving in a void.
        tl.add(rules, { scaleX: 1, duration: 700, delay: stagger(60) }, 0);

        // BEAT 2 — the name rises out of its own clip, given name then family
        // name. Two objects, 120ms apart: a page turning, not a typewriter.
        tl.add(
            words,
            {
                opacity: 1,
                translateY: '0%',
                duration: 820,
                ease: EASE_IN_OUT_QUART,
                delay: stagger(120),
            },
            60,
        );

        // The record follows as one soft cascade. 80ms × 6 rows caps the total
        // stagger under half a second, so the last row is not still arriving
        // after the reader has finished the first.
        tl.add(
            risers,
            { opacity: 1, translateY: 0, duration: 420, delay: stagger(80) },
            300,
        );

        // BEAT 4 — the stamp lands last, and lands crooked. A stamp applied by
        // hand is never square, and the -1.5° is the entire difference between
        // "printed object" and "graphic of a printed object".
        if (stamp) {
            tl.add(
                stamp,
                { opacity: 1, rotate: -1.5, scale: 1, duration: 420 },
                640,
            );
        }

        return () => {
            tl.pause();
            // Leave the plate printed, never half-printed, on an early unmount.
            utils.set(rules, { scaleX: 1 });
            utils.set(words, { opacity: 1, translateY: '0%' });
            utils.set(risers, { opacity: 1, translateY: 0 });
            if (stamp) utils.set(stamp, { opacity: 1, rotate: -1.5, scale: 1 });
        };
        // Deliberately empty: replaying the entrance on a theme change reads as
        // a bug, and nothing in this effect closes over reactive state.
    }, []);

    return (
        <Box
            component="section"
            ref={rootRef}
            // `hero-section` is the hook the print stylesheet already reaches for.
            className="ac-hero hero-section"
        >
            <div className="ac-plate">
                {/* ── Head: the running head of a catalogue page ───────────── */}
                <div className="ac-rule ac-rule--heavy" aria-hidden />
                <div className="ac-head" data-ac-rise>
                    <span className="ac-caps">Catalogue of Work</span>
                    <span className="ac-caps ac-head-right">
                        Collection of One · Complete
                    </span>
                </div>
                <div className="ac-rule" aria-hidden />

                {/* ── The stamp ────────────────────────────────────────────────
                    aria-hidden: the accession number is a conceit of this
                    perspective, not information about the person, and reading
                    "A C C dot 2 0 2 6 dot 0 0 1" aloud before the name would be
                    the skin talking over the résumé. */}
                {title && (
                    <div className="ac-stamp no-print" aria-hidden>
                        <span className="ac-stamp-word">Accession</span>
                        <span className="ac-stamp-no">{STAMP_YEAR}</span>
                        {location && (
                            <>
                                <span className="ac-stamp-rule" />
                                <span className="ac-stamp-word">{location}</span>
                            </>
                        )}
                    </div>
                )}

                {/* ── The object ──────────────────────────────────────────── */}
                {title && (
                    <Typography component="h1" className="ac-name">
                        <span className="ac-word">
                            <span>{given}</span>
                        </span>
                        {family && (
                            <span className="ac-word ac-word--italic">
                                <span>{family}</span>
                            </span>
                        )}
                    </Typography>
                )}

                {/* ── The record ──────────────────────────────────────────── */}
                {record.length > 0 && (
                    <dl className="ac-record">
                        {record.map((row) => (
                            <div className="ac-row" key={row.label} data-ac-rise>
                                <dt className="ac-caps ac-row-label">{row.label}</dt>
                                <dd className="ac-row-value">
                                    {row.values.map((v) => (
                                        <span className="ac-cell" key={v}>
                                            {v}
                                        </span>
                                    ))}
                                    {/* The row's hairline lives INSIDE the `dd`
                                        (flow content) rather than beside it:
                                        `dl > div` may only contain `dt`/`dd`,
                                        and a rule this skin draws on purpose is
                                        not worth invalid markup. */}
                                    <div className="ac-rule ac-rule--row" aria-hidden />
                                </dd>
                            </div>
                        ))}
                    </dl>
                )}

                {/* ── The note ─────────────────────────────────────────────────
                    The catalogue's own annotation, and the one place the frame
                    is deliberately contradicted: an on-device language model,
                    described in a serif italic on paper stock. */}
                <p className="ac-note" data-ac-rise>
                    {ASSISTANT_LINE}
                </p>

                {/* ── The apparatus ───────────────────────────────────────── */}
                <Stack
                    data-ac-rise
                    className="no-print ac-actions"
                    direction="row"
                    flexWrap="wrap"
                    alignItems="center"
                    gap={2}
                >
                    <Button variant="contained" color="primary" onClick={openChat}>
                        Ask the assistant
                    </Button>
                    <Button
                        variant="text"
                        color="inherit"
                        className="ac-link"
                        href="#experience"
                    >
                        Provenance
                    </Button>
                    <Button
                        variant="text"
                        color="inherit"
                        className="ac-link"
                        href="#projects"
                    >
                        The collection
                    </Button>
                </Stack>

                <div className="ac-rule ac-rule--heavy" aria-hidden />
            </div>
        </Box>
    );
}
